server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5342/aleia
    username: postgres
    password: lozinka
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: campaign
    show-sql: true
  flyway:
    schemas: campaign
  main:
    web-application-type: servlet